# Merchant/category config
# Matching is SUBSTRING-based (case-insensitive).
# Keep tokens short & distinctive (e.g., "WHOLEFDS" instead of full line)

version: 1

defaults:
  case_sensitive: false         # match without worrying about case
  match_type: substring         # "substring" | "regex" (we use substring)
  category_for_unknown: null    # leave unknowns blank so we can review
  priority: 100                 # future use (if you add per-rule priorities)

# Categories you want to see in your dashboard
categories:
  - dining
  - groceries
  - shopping
  - transportation
  - travel
  - auto_service
  - health_wellness
  - fitness_sports
  - government_fees
  - credit_card_payment
  - refunds_income
  - utilities        # exists for your ISP, but no generic mappings below

# Categories that should be treated as NON-SPEND flows in the script
non_spend_categories:
  - credit_card_payment
  - refunds_income
  - transfer
  - loan_payment
  - income
  - internal_move

# (Optional) categories that you want the dashboard to mark as necessities
necessity_flags:
  groceries: true
  transportation: true
  utilities: true

# -------------------------------------------------
# Merchant/category mapping (substring matches)
# -------------------------------------------------
mapping:
  # --- Dining / Fast food ---
  dining:
    - APPLEBEES
    - IHOP
    - PANDA EXPRESS
    - IN-N-OUT
    - RAISING CANES
    - CHEBA HUT
    - DOMINO'S
    - RIVER BUFFET
    - VEGAS BAKERY

  # --- Groceries ---
  groceries:
    - WHOLEFDS        # Chase abbreviations for Whole Foods
    - WHOLE FDS
    - HARRIS TEETER
    - PUBLIX
    - LIDL
    - FOOD LION

  # --- General Shopping / Retail & Marketplaces ---
  shopping:
    - TARGET
    - AMAZON MKTPL
    - AMAZON MKTPLACE PMTS
    - AMAZON PRIME
    - AMAZON COM
    - WALMART COM
    - MACYS
    - BR FACTORY
    - EBAY
    - ASOS COM

  # --- Transportation / Gas / Parking ---
  transportation:
    - ARCO
    - TERRIBLE HERBST
    - THEPARKINGSPOT
    - 76 - SPEEDEE
    - S&S

  # --- Travel (airlines, parking vendors you want as travel) ---
  travel:
    - SPIRIT AIRLINES
    - THEPARKINGSPOT-   # treat ECW location as travel

  # --- Auto service / Dealers ---
  auto_service:
    - STEELE AUTOMOTIVE
    - FLETCHER JONES
    - MASTER AUTOMOTIVE

  # --- Health / Wellness / Fitness ---
  health_wellness:
    - KNEADED ENERGY
    - VAGARO WHOLE BODY HEAL
    - ATHLETICO

  fitness_sports:
    - JIU JITSU
    - US JIU JITSU FEDERATIO
    - SPECTATION SPORTS

  # --- Government / Legal / Courts / Fees ---
  government_fees:
    - DMV
    - NV GCB
    - NC COURT PAYMENTS
    - SOUTHERN NV HEALTH DIST
    - BULLET LEGAL SERVI
    - ITICKET LAW

  # --- Card payments / Transfers / Non-spend flows ---
  credit_card_payment:
    - AUTOMATIC PAYMENT - THANK
    - INTERNET PAYMENT - THANK YOU
    - DIRECTPAY
    - FULL BALANCE
    - PAYMENT THANK
    - PAYMENT - THANK
    - ACCTVERIFY
    - CASHBACK BONUS REDEMPTION

  # --- Income / Refunds (keep separate from spend) ---
  refunds_income:
    - CASHBACK BONUS REDEMPTION
