name: Build & Enrich Latest

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
      PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
      PLAID_ENV: ${{ secrets.PLAID_ENV }}
      PLAID_ACCESS_TOKENS: ${{ secrets.PLAID_ACCESS_TOKENS }}
      OUTPUT_DIR: data/raw
      # Azure keys optional; AI cells no-op if unset
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
      AZURE_OPENAI_EMBEDDINGS: ${{ secrets.AZURE_OPENAI_EMBEDDINGS }}
      AZURE_OPENAI_API_VERSION: 2024-02-15-preview

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install papermill ipykernel

      - name: Prepare runtime state
        run: |
          mkdir -p .state
          echo "${PLAID_ACCESS_TOKENS}" > .state/access_tokens.json
          if [ ! -f .state/plaid_cursors.json ]; then echo "{}" > .state/plaid_cursors.json; fi

      - name: Run build notebook
        run: |
          papermill scripts/build_latest.ipynb scripts/build_latest.ipynb

      - name: Run enrich notebook
        run: |
          papermill scripts/enrich_transactions.ipynb scripts/enrich_transactions.ipynb

      - name: Commit outputs if changed
        shell: bash
        run: |
          set -euo pipefail

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Always add latest.csv (verified earlier)
          git add -f data/raw/latest.csv

          # Add merchants_dim.csv if present
          if [ -f config/merchants_dim.csv ]; then
            git add -f config/merchants_dim.csv
          fi

          # Optional processed/insight files (force-add to bypass any ignore edge cases)
          files=(
            "data/processed/latest_enriched.csv"
            "data/processed/digest_latest.txt"
            "data/processed/goal_nudges_latest.txt"
            "data/processed/insights/wow_subject.csv"
            "data/processed/insights/wow_subject.txt"
            "data/processed/insights/wow_summary.md"
            "data/processed/insights/wow_summary.html"
            "data/processed/insights/mom_subject.csv"
            "data/processed/insights/mom_subject.txt"
            "data/processed/insights/mom_summary.md"
            "data/processed/insights/mom_summary.html"
            "data/processed/insights/digest_latest.json"
            "data/processed/insights/digest_latest.md"
            "data/processed/insights/digest_latest_flat.csv"
            "data/processed/insights/mom_flat.csv"
          )
          for f in "${files[@]}"; do
            if [ -f "$f" ]; then
              git add -f "$f"
            fi
          done

          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update data & insights [skip ci]"
            git push
          fi
          fi