name: Pull Plaid Transactions

on:
  workflow_dispatch: {}   # allow manual runs
  schedule:
    # Weekly: Mondays 11:00 UTC (04:00 Pacific)
    - cron: "0 11 * * 1"
    # Monthly: 1st of month 11:05 UTC
    - cron: "5 11 1 * *"

permissions:
  contents: write

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run pull notebook (headless with papermill)
        env:
          PLAID_ENV: production
          PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
          PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
          PLAID_ACCESS_TOKENS: ${{ secrets.PLAID_ACCESS_TOKENS }}
        run: |
          python -m pip install --upgrade pip
          pip install papermill ipykernel plaid-python python-dateutil python-dotenv
          python -m ipykernel install --user --name python3 --display-name "Python 3"
          papermill scripts/pull_transactions.ipynb executed_pull_transactions.ipynb -k python3

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: plaid pull $(date -u +%F)"
            git push
          else
            echo "No changes to commit."
          fi