name: Build & Enrich Latest

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 6"   # Friday evening Pacific year-round

permissions:
  contents: write

concurrency:
  group: spending-dashboard-build-latest
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      PYTHONUNBUFFERED: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PIP_NO_PYTHON_VERSION_WARNING: "1"

      PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
      PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
      PLAID_ENV: ${{ secrets.PLAID_ENV }}
      PLAID_ACCESS_TOKENS: ${{ secrets.PLAID_ACCESS_TOKENS }}
      OUTPUT_DIR: data/raw

      # Azure keys optional (enrich will no-op AI if these are unset)
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
      AZURE_OPENAI_EMBEDDINGS: ${{ secrets.AZURE_OPENAI_EMBEDDINGS }}
      AZURE_OPENAI_API_VERSION: 2024-02-15-preview

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install papermill ipykernel

      - name: Prepare runtime state
        run: |
          mkdir -p .state
          printf '%s' "${PLAID_ACCESS_TOKENS}" > .state/access_tokens.json
          [ -f .state/plaid_cursors.json ] || echo '{}' > .state/plaid_cursors.json

      - name: Run build notebook
        run: |
          papermill scripts/build_latest.ipynb scripts/build_latest.ipynb
          echo "After build (listing data/raw):"
          ls -la "$GITHUB_WORKSPACE/data/raw" || true
          test -f "$GITHUB_WORKSPACE/data/raw/latest.csv" || (echo "latest.csv missing after build" && exit 1)

      - name: Run enrich notebook
        run: |
          papermill scripts/enrich_transactions.ipynb scripts/enrich_transactions.ipynb

- name: Commit outputs if changed
  run: |
    set -euo pipefail
    git config user.name "github-actions[bot]"
    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    # Always add latest.csv
    git add data/raw/latest.csv

    # merchants_dim.csv if present
    [ -f config/merchants_dim.csv ] && git add config/merchants_dim.csv || true

    # insights artifacts (allowed by .gitignore exceptions you added)
    [ -f data/processed/insights/digest_latest.json ] && git add data/processed/insights/digest_latest.json || true
    [ -f data/processed/insights/digest_latest.md ] && git add data/processed/insights/digest_latest.md || true
    [ -f data/processed/insights/digest_latest_flat.csv ] && git add data/processed/insights/digest_latest_flat.csv || true

    # Only add embeddings if NOT ignored (prevents 'ignored by .gitignore' failure)
    if [ -f vectorstore/embeddings.parquet ]; then
      if git check-ignore -q vectorstore/embeddings.parquet; then
        echo "vectorstore/embeddings.parquet is gitignored; skipping."
      else
        git add vectorstore/embeddings.parquet
      fi
    fi

    if git diff --staged --quiet; then
      echo "No changes to commit."
    else
      git commit -m "Auto-update latest & insights [skip ci]"
      git push
    fi
