name: Build latest.csv

on:
  workflow_dispatch:
  schedule:
    - cron: "29 */6 * * *"   # every 6 hours at :29

permissions:
  contents: write

concurrency:
  group: build-latest
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
      PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
      PLAID_ENV: ${{ secrets.PLAID_ENV }}
      PLAID_ACCESS_TOKENS: ${{ secrets.PLAID_ACCESS_TOKENS }}
      OUTPUT_DIR: data/raw

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Ensure papermill + ipykernel present to execute notebooks
          pip install papermill ipykernel

      - name: Create runtime state (tokens/cursor)
        run: |
          mkdir -p .state
          # Write PLAID_ACCESS_TOKENS JSON into .state/access_tokens.json
          echo "${PLAID_ACCESS_TOKENS}" > .state/access_tokens.json
          # Ensure cursors file exists
          if [ ! -f .state/plaid_cursors.json ]; then echo "{}" > .state/plaid_cursors.json; fi

      - name: Execute notebook -> latest.csv
        run: |
          # Execute scripts/build_latest.ipynb in-place
          papermill \
            scripts/build_latest.ipynb \
            scripts/build_latest.ipynb

      - name: Commit latest.csv (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/raw/latest.csv
          if ! git diff --staged --quiet; then
            git commit -m "Auto-update latest.csv [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
