name: Build & Enrich latest.csv

on:
  workflow_dispatch: {}
  schedule:
    - cron: "29 */6 * * *"   # every 6 hours at :29

permissions:
  contents: write

concurrency:
  group: build-latest
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
      PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
      PLAID_ENV: ${{ secrets.PLAID_ENV }}
      PLAID_ACCESS_TOKENS: ${{ secrets.PLAID_ACCESS_TOKENS }}
      OUTPUT_DIR: data/raw
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
      AZURE_OPENAI_EMBEDDINGS: ${{ secrets.AZURE_OPENAI_EMBEDDINGS }}
      AZURE_OPENAI_API_VERSION: 2024-02-15-preview

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug: show repo tree & head
        run: |
          set -eux
          ls -la
          git rev-parse HEAD
          echo "---- requirements.txt (raw) ----"
          cat requirements.txt || true

      - name: Install deps (sanitize requirements)
        run: |
          set -eux
          # Strip any accidental 'azure-ai-openai' lines so install never breaks
          sed -i '/^[[:space:]]*azure-ai-openai[[:space:]]*$/d' requirements.txt || true
          echo "---- requirements.txt (sanitized) ----"
          cat requirements.txt
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install papermill ipykernel

      - name: Create runtime state (tokens/cursor)
        run: |
          mkdir -p .state
          echo "${PLAID_ACCESS_TOKENS}" > .state/access_tokens.json
          if [ ! -f .state/plaid_cursors.json ]; then echo "{}" > .state/plaid_cursors.json; fi

      - name: Execute build notebook -> data/raw/latest.csv
        run: |
          papermill scripts/build_latest.ipynb scripts/build_latest.ipynb

      - name: Execute enrich notebook -> overwrite data/raw/latest.csv
        run: |
          papermill scripts/enrich_transactions.ipynb scripts/enrich_transactions.ipynb

      - name: Commit outputs (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/raw/latest.csv config/merchants_dim.csv
          if ! git diff --staged --quiet; then
            git commit -m "Auto-update latest.csv & merchants_dim [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
